### ISSUE TITLE
Ready this transformer plugin for GraphQL Transformer v2

### ISSUE THREAD

**Issue by renebrandel** [flogy/graphql-ttl-transformer#12]
👋  This is Rene from the AWS Amplify team! First off, **THANK YOU** for your amazing plugin! 

I have some great news to share, we've rewritten the GraphQL Transformer plugin from the ground up to take advantage of some really amazing capabilities. All the details here: https://github.com/aws-amplify/amplify-cli/issues/6217#issuecomment-929677992 

### How to migrate your plugin to GraphQL Transformer v2
In order to make this plugin forward compatible with GraphQL Transformer v2, you need to make some tiny adjustments to the classes you inherit from. Migration steps here: https://gist.github.com/renebrandel/0b9537e2016e3dd9ed6d794b30b2e3f4

Happy to also hop on a call with you to walk you through the process. Email me at any time: renbran at amazon dot com

**Comment by samputer** [comment]
@flogy - thanks for this excellent transformer. I've been using it successfully for a few months now.

I was wondering if you had plans to update this to V2 as per this issue? I took a quick stab at it myself but found it to be a little more involved than @renebrandel 's above comment would suggest. I'd be happy to help with this.

**Comment by renebrandel** [comment]
@samputer - the ttl transformer probably offers the best experience but if you're looking for an escape hatch to self-configure, you can try to use one of our extensibility features `amplify override api`. More here: https://docs.amplify.aws/cli/graphql/override/#customize-amplify-generated-resources-for-model-directive

**Comment by flogy** [comment]
Hi @samputer 

Thanks for the kind words and happy to hear you were using the transformer successfully!

I will definitely take a look at it as well and see whether it makes more sense to do the upgrade or just use `amplify override api` as @renebrandel suggests. Were there any specific problems when you tried to do the upgrade that I should be aware of?

**Comment by hisham** [comment]
Yes the instructions in https://gist.github.com/renebrandel/0b9537e2016e3dd9ed6d794b30b2e3f4 are not complete. There's more to it than that when upgrading a custom transformer. I'm in the process of upgrading my custom transformers themselves. Referencing https://github.com/sirvan3tr/amplify-graphql-default-owner-transformer/blob/main/src/amplify-graphql-default-owner-transformer.ts and https://docs.amplify.aws/cli/plugins/authoring/#authoring-custom-graphql-transformers--directives has been helpful. 

I don't think it would be too hard to upgrade this plugin to v2, just needs some experimentation as amplify custom gql transformer documentation is a bit sparse. I might take a crack at it after I upgrade my own custom directives, or just use the override feature which is tempting, not sure yet.

**Comment by hisham** [comment]
I started upgrading this plugin, but it seems Cdk DynamoDB table interface does not have a public way to update the timeToLiveAttribute after the table has been constructed. See https://github.com/aws/aws-cdk/issues/13106. 

But I was able to at least set the TTL by accessing a private property. Not sure what happens if you try to change the ttl attribute on a table with existing other ttl attribute. I'll clean up my code and commit what I have in next few days if it helps.

**Comment by hisham** [comment]
I went ahead and made a draft PR with the core functionality upgraded. I also published an npm package here if anyone needs to use it: https://www.npmjs.com/package/graphql-ttl-transformer-v2-beta. I marked as beta since I did not bother to update unit tests and readme. I also ended up using a private property of the DynamoDB Table object to make this change. Couldn't find another way to do this.

**Comment by flogy** [comment]
Hi @hisham 

Thank you very much for your efforts here! I will take a look at the changes and integrate it into this library as soon as possible, so we could reuse it under the same npm package for existing users. Currently a bit busy but I hope I can check this soon!

**Comment by xylanreeves** [comment]
Hey guys! any update on this?

**Comment by flogy** [comment]
A new version of this transformer was released which is now compatible with GraphQL Transformer v2 🚀 

Sorry for the long delay and huge thanks to @hisham for the contribution!
