### ISSUE TITLE
Question!

### ISSUE THREAD

**Issue by SaileshKumar** [flogy/graphql-ttl-transformer#13]
Hi, thank you for writing this!

Question for you - is the int option saying I can have a "dynamic" ttl like 30 days, instead of a specific timestamp? What would the units be there?

Thank you!

**Comment by flogy** [comment]
Hi @SaileshKumar 

Thank you for using this library and for your question. Unfortunately, it is not possible to have a dynamic TTL (DynamoDB does not offer it). A timestamp is always required. The `Int` option just defines the field type but it works exactly the same.

Cheers,
Florian
