### ISSUE TITLE
An error occurred during the push operation: / acc.getResource is not a function

### ISSUE THREAD

**Issue by gouthasnm** [flogy/graphql-ttl-transformer#14]
The below line seems to fail when I do amplify push.

https://github.com/flogy/graphql-ttl-transformer/blob/3423eb4e7321b68d4382889c019488443f25b61a/src/ttl-transformer.ts#L54

I get the error:
An error occurred during the push operation: /
acc.getResource is not a function

**Comment by flogy** [comment]
Hi @gouthasnm 

How does your schema look like? And which Amplify CLI version are you using? This will help me debug the issue.

Thanks.

Cheers,
Florian

**Comment by gouthasnm** [comment]
Hi @flogy , Thank you for responding to my issue. I am using Amplify 8.3.1

Below is my schema.


input AMPLIFY { globalAuthRule: AuthRule = { allow: public } } # FOR TESTING ONLY!

type FBStatusInfo @model {
  id: ID! @primaryKey #(sortKeyFields: ["attribkey"])  
  status: Boolean
  results: String
  createdAt: AWSDateTime
  updatedAt: AWSDateTime
  expirationUnixTime: AWSTimestamp  @ttl
}

type Subscription {
  onCreateFBStatusInfoAppSyncJobID(id: ID!): FBStatusInfo
    @aws_subscribe(mutations: ["createFBStatusInfo"])
}

type Query {
    batchGetFBStatus(ids: [ID]): [FBStatusInfo]
}

**Comment by gouthasnm** [comment]
Update: the markdown language is making first t in @ ttl as capital. But it is ttl not Ttl

**Comment by scott-caylent** [comment]
I'm getting the same error using the most recent version of Amplify. Here's my mode: 

`type JobPost
	@model
	@auth(
		rules: [
			...
		]
	) {
	  id: ID!
	  ttl: Int! @ttl 
	}`

**Comment by hisham** [comment]
I believe this error is because you guys are on GraphQl Transformer v2 (https://aws.amazon.com/blogs/mobile/aws-amplify-announces-the-new-graphql-transformer-v2-more-feature-rich-flexible-and-extensible/), while this plugin is designed for GraphQL Transformer v1. 

See https://github.com/flogy/graphql-ttl-transformer/issues/12

**Comment by scott-caylent** [comment]
> I believe this error is because you guys are on GraphQl Transformer v2 (https://aws.amazon.com/blogs/mobile/aws-amplify-announces-the-new-graphql-transformer-v2-more-feature-rich-flexible-and-extensible/), while this plugin is designed for GraphQL Transformer v1.
> 
> See #12

Thanks for the reply. I saw that so I ended up just writing a lambda to clean up my outdated records for the time being. I'll swap over to using this  library once it's compatible with V2.

**Comment by flogy** [comment]
A new version of this transformer was released which is now compatible with GraphQL Transformer v2 🚀 This should now fix the issue.

Huge thanks to @hisham for the contribution!
