### ISSUE TITLE
Install transformer without transform.conf.json configuration?

### ISSUE THREAD

**Issue by rudyhadoux** [flogy/graphql-ttl-transformer#2]
Hi,
will this feature be automated in the future ?
I have no transform.conf.json file in my Amplify back-end.

**Comment by flogy** [comment]
How do you mean automated? I believe the manual configuration in the `transform.conf.json` is mandatory for custom transformers. If it does not exist in your project you can probably just create it yourself.

**Comment by rudyhadoux** [comment]
For @auth or @versioned by example, there is no need to add anything.

**Comment by flogy** [comment]
I believe that this is because those are coming with Amplify. Not sure how to avoid it...

If somebody knows how to install custom transformers without having to manually configure it in `transform.conf.json`, please provide some insights.

I'll leave this open for now.

**Comment by rudyhadoux** [comment]
OK great.

**Comment by joekiller** [comment]
I cannot confirm if this would work, but reading [the docs about the transform.conf.json](https://docs.amplify.aws/cli/reference/files/#transformconfjson), you may want to try `amplify api update`. You may want to try making the codegen re-generate the API by removing and adding the API back, understanding not to push while doing so.
