### ISSUE TITLE
Does not work with Amplify CLI v11

### ISSUE THREAD

**Issue by hisham** [flogy/graphql-ttl-transformer#20]
This plugin needs to be upgraded to use CDK v2, otherwise, you will get the "construct does not have an associated node. All constructs must extend the "Construct" base class" error when pushing. 

See https://github.com/aws-amplify/amplify-category-api/issues/1404

**Comment by flogy** [comment]
Released in https://github.com/flogy/graphql-ttl-transformer/releases/tag/2.0.1

Thank you very much for your contribution! 🥳️
