### ISSUE TITLE
Build failure: "Unable to import custom transformer module(graphql-ttl-transformer)"

### ISSUE THREAD

**Issue by jeremyburton** [flogy/graphql-ttl-transformer#3]
Hi and thanks for this transformer,

I have followed your npm install instruction and also added a `transformers` field with `graphql-ttl-transformer` to `transform.conf.json` like this:

``` json
{
    "Version": 5,
    "ElasticsearchWarning": true,
    "transformers": [
        "graphql-ttl-transformer"
    ]
}
```

I can successfully deploy the backend with `amplify push` but when I try to deploy the frontend, the build fails with the following warning: `Unable to import custom transformer module(graphql-ttl-transformer)`.

Here is the relevant part of the build log.

``` txt
2021-01-19T12:01:24.851Z [INFO]: [31mUnable to import custom transformer module(graphql-ttl-transformer).[39m
2021-01-19T12:01:24.852Z [INFO]: [31mYou may fix this error by editing transformers at /codebuild/output/src127667145/src/janky-app/amplify/backend/api/janky/transform.conf.json[39m
2021-01-19T12:01:24.852Z [WARNING]: ✖ An error occurred when pushing the resources to the cloud
2021-01-19T12:01:24.852Z [WARNING]: ✖ There was an error initializing your environment.
2021-01-19T12:01:24.854Z [INFO]: [31minit failed[39m
2021-01-19T12:01:24.855Z [INFO]: [0m/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/import-global/index.js:1[0m
                                 [0mError: Cannot find module '/root/.nvm/versions/node/v12.19.0/lib/node_modules/graphql-ttl-transformer'[0m
                                 [0mRequire stack:[0m
                                 [0m- /root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/import-global/index.js[0m
                                 [0m- /root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/transform-graphql-schema.js[0m
                                 [0m- /root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/push-resources.js[0m
                                 [0m- /root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/amplify-service-migrate.js[0m
                                 [0m- /root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/initializer.js[0m
                                 [0m- /root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/index.js[0m
                                 [0m- /root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/lib/init-steps/s2-initProviders.js[0m
                                 [0m- /root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/lib/commands/init.js[0m
                                 [0m- /root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/lib/index.js[0m
                                 [0m- /root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/bin/amplify[0m
                                 [0m    at Object.module.exports [as default] (/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/import-global/index.js:9:10)[0m
                                 [0m    at /root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/transform-graphql-schema.ts:111:44[0m
                                 [0m    at Array.map (<anonymous>)[0m
                                 [0m    at Object.transformersFactory (/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/transform-graphql-schema.ts:80:8) {[0m
                                 [0m  code: 'MODULE_NOT_FOUND',[0m
                                 [0m  requireStack: [[0m
                                 [0m    '/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/import-global/index.js',[0m
                                 [0m    '/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/transform-graphql-schema.js',[0m
                                 [0m    '/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/push-resources.js',[0m
                                 [0m    '/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/amplify-service-migrate.js',[0m
                                 [0m    '/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/initializer.js',[0m
                                 [0m    '/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/index.js',[0m
                                 [0m    '/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/lib/init-steps/s2-initProviders.js',[0m
                                 [0m    '/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/lib/commands/init.js',[0m
                                 [0m    '/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/lib/index.js',[0m
                                 [0m    '/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/bin/amplify'[0m
                                 [0m  ][0m
                                 [0m}[0m
2021-01-19T12:01:24.871Z [ERROR]: !!! Build failed
2021-01-19T12:01:24.872Z [ERROR]: !!! Non-Zero Exit Code detected
2021-01-19T12:01:24.872Z [INFO]: # Starting environment caching...
2021-01-19T12:01:24.872Z [INFO]: # Environment caching completed
Terminating logging...
```

Any help much appreciated! Thanks

**Comment by flogy** [comment]
Hi @jeremyburton 

Thanks for the error report.

I haven't seen this before why I just went over to the [Amplify CLI codebase](https://github.com/aws-amplify/amplify-cli) and searched for the `Unable to import custom transformer module` error, which seems to be thrown [here](https://github.com/aws-amplify/amplify-cli/blob/59d4a0eb318d2b3ad97be34bda9dee756cf82d74/packages/amplify-provider-awscloudformation/src/transform-graphql-schema.ts#L118). It looks like it first tries to import the dependency from local `node_modules` and only if that's not successful from global packages. As your error message stack contains an `import-global` line, I think it failed at importing it from local `node_modules`. This leads me to the question:

1. Do you actually see the `graphql-ttl-transformer` directory inside you project's `node_modules`?
2. Have you successfully installed it using `npm install --save graphql-ttl-transformer` or could it be that there were some errors when doing so?

Thanks in advance.

**Comment by jeremyburton** [comment]
Hi @flogy 

1. Yes, I can see the `graphql-ttl-transformer` directory in my local project's `node_modules`.
2. It installed successfully as far as I can tell.

<img width="582" alt="graphql-ttl-transformer_in_node_modules" src="https://user-images.githubusercontent.com/7051714/105058313-fdbeb100-5a6d-11eb-97a1-e7496da55627.png">

**Comment by flogy** [comment]
Hm, okay. Is it possible to share your repository so I could have a look?

**Comment by jeremyburton** [comment]
I should probably have said that this was a remote build on AWS Amplify (CI/CD), not a local build. I don't commit my `node_modules` directory to my repository, so I guess AWS installs modules as per package.json.

**Comment by flogy** [comment]
Oh, I see. Maybe you could inspect the build folder or log output on CI/CD to also verify if the `graphql-ttl-transformer` actually was installed successfully?

It just seems to be the most likely reason for this error when looking at the [related Amplify CLI code](https://github.com/aws-amplify/amplify-cli/blob/59d4a0eb318d2b3ad97be34bda9dee756cf82d74/packages/amplify-provider-awscloudformation/src/transform-graphql-schema.ts#L118). 🤔

**Comment by jeremyburton** [comment]
The logging I included in my initial report was from the AWS Amplify CI/CD build process. I have tried building the project locally and that seems fine. I agree that it seems that the `graphql-ttl-transformer` module isn't being found during the build process but I don't understand why.

**Comment by flogy** [comment]
What CI/CD system are you using exactly? Could you describe it's configuration, please?

**Comment by jeremyburton** [comment]
I'm using AWS Amplify Console with the default build settings:

```
version: 1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: dist
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

**Comment by jeremyburton** [comment]
If you're not already familiar with using the hosting side of the Amplify Console, these docs might be helpful: 
https://docs.aws.amazon.com/amplify/latest/userguide/welcome.html
https://docs.aws.amazon.com/amplify/latest/userguide/build-settings.html

**Comment by jeremyburton** [comment]
I have linked branches of my repository to an App in the AWS Amplify Console so that whenever I push changes it automatically attempts to create a new build and deploy it. All my other node packages currently build fine with this setup. It only started to fail when I added the `graphql-ttl-transformer` package.

**Comment by flogy** [comment]
Hm, I really never used that before. I'd just go with some trial and error stuff at this point:

```yaml
version: 1
backend:
  phases:
    build:
      commands:
        - npm i -S graphql-ttl-transformer
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: dist
    files:
      - '**/*'
```

What I've modified here:

1. Added `- npm i -S graphql-ttl-transformer` to the backend build commands.
2. Removed the caching configuration from the frontend (should not be a problem as I guess the frontend build is run separately).

Does that work? And if not, is it still the same error in the log output after those modifications?

**Comment by jeremyburton** [comment]
Yes, that worked 😀 The backend built successfully and you can see that `graphql-ttl-transformer` was installed this time:

```
                                 # Starting phase: build
                                 # Executing command: npm i -S graphql-ttl-transformer
2021-01-19T17:04:04.484Z [WARNING]: npm WARN react-native-get-random-values@1.5.0 requires a peer of react-native@>=0.56 but none is installed. You must install peer dependencies yourself.
2021-01-19T17:04:04.486Z [WARNING]: 
2021-01-19T17:04:04.486Z [INFO]: + graphql-ttl-transformer@1.1.0
                                 added 41 packages from 62 contributors and audited 1626 packages in 9.276s
```
Do you know if/why removing the cache config is necessary? I don't like changing the build settings without fully understanding the consequences (which I don't in this case).

**Comment by jeremyburton** [comment]
Is there anything you can do on the module side that would remove the neccessity for the custom build settings in AWS Amplify Console?

**Comment by flogy** [comment]
I'm not sure how the caching works exactly. I just thought it might sense to try deactivating it to make sure it is not preventing the CI/CD process from re-installing the dependencies and thus not installing `graphql-ttl-transformer`.

I believe it should not be necessary to also remove caching. It should be enough to just add the additional build command to install the library manually.

But I can't tell you if this is best practice or not. Maybe you should also check with the guys from [amplify-console](https://github.com/aws-amplify/amplify-console).

I don't think it is possible to make it work by just changing something at this module as the problem seems to be coming from the way Amplify Console handles external dependencies.

As it seems to be working, I'll close this issue now. If there are any new insights about whether removing the caching is necessary or if ust adding the install command was enough, it would be helpful if you could add another comment about it though (for people looking for it in the future) 🙂

Thanks! May this module serve you well in your projects!

**Comment by Baazigar007** [comment]
Saved my life . Thanks, removing caching helped me with this. It was a caching issue.

**Comment by leighton-tidwell** [comment]
I would like to add to this and say that the only way I could get it to work was by adding the install command to my backend build **as well as** removing the caching.

Also unrelated, but perhaps in the documentation it would be important to note that the transformer will not automatically switch the TTL attribute (example: from _ttl to "expiryTime") if the table has already been created.. I just found that out! Probably an obvious thing to know for some, but I'm a little new to Amplify as a whole.

**Comment by joekiller** [comment]
Just wanted to note here the solution that worked for me was upgrading npm and installing the plugin before the push ie:

```
version: 1
backend:
  phases:
    build:
      commands:
        - npm install -g npm@latest
        - npm install graphql-ttl-transformer
        - amplifyPush --simple
 ```
